services:
  app:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: short_links_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://test-user:Test123%40@db:5432/short_links?schema=public
    depends_on:
      - db
  db:
    image: postgres:16.6
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_DB: short_links
      POSTGRES_USER: test-user        # Usuario test
      POSTGRES_PASSWORD: Test123@     # Contraseña para el usuario test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Usuario test
      PGADMIN_DEFAULT_PASSWORD: admin123       # Contraseña para el usuario test
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
